"""empty message

Revision ID: 78ace169776d
Revises: b62de5541991
Create Date: 2021-07-13 11:42:31.552917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78ace169776d'
down_revision = 'b62de5541991'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cart_product_id_fkey', 'cart', type_='foreignkey')
    op.add_column('stripe_product', sa.Column('stripe_product_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stripe_product', 'stripe_product_id')
    op.create_foreign_key('cart_product_id_fkey', 'cart', 'product', ['product_id'], ['id'])
    # ### end Alembic commands ###
