"""empty message

Revision ID: d07deee49aa1
Revises: 8ecf7edde01c
Create Date: 2021-07-13 11:30:32.772013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07deee49aa1'
down_revision = '8ecf7edde01c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stripe_product', sa.Column('stripe_product_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stripe_product', 'stripe_product_id')
    # ### end Alembic commands ###
